export const jobs = [
  {
    id: 1,
    title: "Assistant Director",
    department: "Federal Investigation Agency (FIA)",
    commission: "FPSC",
    grade: "BPS-17",
    seats: 45,
    lastDate: "2026-05-15",
    publishDate: "2026-04-10",
    location: "Federal",
    subjects: ["General Knowledge", "Pakistan Studies", "English", "Current Affairs"],
    description: "Applications are invited from Pakistani nationals for the post of Assistant Director in the Federal Investigation Agency. The selected candidates will be responsible for conducting investigations, gathering intelligence, and maintaining law & order.",
    eligibility: "Masters Degree (2nd Division) from a recognized university",
    age: "21-30 years",
    source: "FPSC",
    sourceUrl: "https://fpsc.gov.pk",
    featured: true,
    mcqCount: 120,
    prepReady: true,
  },
  {
    id: 2,
    title: "Sub-Inspector",
    department: "Punjab Police",
    commission: "PPSC",
    grade: "BPS-14",
    seats: 500,
    lastDate: "2026-05-20",
    publishDate: "2026-04-12",
    location: "Punjab",
    subjects: ["General Knowledge", "Pakistan Studies", "Islamiat", "English", "Basic Math"],
    description: "Punjab Public Service Commission invites applications for Sub-Inspector posts in Punjab Police. Candidates will undergo physical and written tests.",
    eligibility: "Graduation (2nd Division) from HEC recognized university",
    age: "20-28 years",
    source: "PPSC",
    sourceUrl: "https://ppsc.gop.pk",
    featured: true,
    mcqCount: 200,
    prepReady: true,
  },
  {
    id: 3,
    title: "Junior Clerk",
    department: "Sindh Education Department",
    commission: "SPSC",
    grade: "BPS-11",
    seats: 320,
    lastDate: "2026-05-10",
    publishDate: "2026-04-08",
    location: "Sindh",
    subjects: ["General Knowledge", "Sindhi", "English", "Computer Basics"],
    description: "Sindh Public Service Commission announces recruitment for Junior Clerk positions across various departments of Sindh Government.",
    eligibility: "Intermediate (2nd Division) with Typing Speed 30 WPM",
    age: "18-28 years",
    source: "SPSC",
    sourceUrl: "https://spsc.gov.pk",
    featured: false,
    mcqCount: 80,
    prepReady: true,
  },
  {
    id: 4,
    title: "CSS Officer",
    department: "Central Superior Services",
    commission: "CSS",
    grade: "BPS-17/18",
    seats: 300,
    lastDate: "2026-06-01",
    publishDate: "2026-04-01",
    location: "Federal",
    subjects: ["English Essay", "Current Affairs", "Pakistan Affairs", "Islamiat", "Optional Subjects"],
    description: "The most prestigious civil service exam of Pakistan conducted by FPSC. Successful candidates are inducted into various civil services groups.",
    eligibility: "Graduation (at least 2nd Division) age 21-30 years",
    age: "21-30 years",
    source: "FPSC",
    sourceUrl: "https://fpsc.gov.pk",
    featured: true,
    mcqCount: 500,
    prepReady: true,
  },
  {
    id: 5,
    title: "Network Engineer",
    department: "Pakistan Telecommunication Authority",
    commission: "NTS",
    grade: "BPS-17",
    seats: 30,
    lastDate: "2026-05-25",
    publishDate: "2026-04-14",
    location: "Federal",
    subjects: ["Computer Science", "Networking", "General Knowledge", "English"],
    description: "PTA is seeking qualified Network Engineers with expertise in telecommunications infrastructure management and network security.",
    eligibility: "BE/BS in Computer Science/Telecom Engineering",
    age: "22-32 years",
    source: "NTS",
    sourceUrl: "https://nts.org.pk",
    featured: false,
    mcqCount: 90,
    prepReady: false,
  },
  {
    id: 6,
    title: "Tax Inspector",
    department: "Federal Board of Revenue",
    commission: "FPSC",
    grade: "BPS-16",
    seats: 180,
    lastDate: "2026-05-30",
    publishDate: "2026-04-16",
    location: "Federal",
    subjects: ["Accountancy", "Economics", "General Knowledge", "English", "Pakistan Studies"],
    description: "FBR requires Tax Inspectors for collection of taxes and enforcement of tax laws across Pakistan.",
    eligibility: "Graduation in Commerce/Economics/Accounting",
    age: "20-30 years",
    source: "FPSC",
    sourceUrl: "https://fpsc.gov.pk",
    featured: false,
    mcqCount: 150,
    prepReady: true,
  },
];

export const subjects = [
  { id: 1, name: "General Knowledge", icon: "🌍", mcqCount: 850, color: "#1B4FD8" },
  { id: 2, name: "Pakistan Studies", icon: "🇵🇰", mcqCount: 620, color: "#16A34A" },
  { id: 3, name: "Islamiat", icon: "☪️", mcqCount: 480, color: "#D97706" },
  { id: 4, name: "English Grammar", icon: "📝", mcqCount: 540, color: "#7C3AED" },
  { id: 5, name: "Current Affairs", icon: "📰", mcqCount: 380, color: "#E11D48" },
  { id: 6, name: "Everyday Science", icon: "🔬", mcqCount: 290, color: "#0891B2" },
  { id: 7, name: "Basic Math", icon: "🔢", mcqCount: 410, color: "#EA580C" },
  { id: 8, name: "Computer Basics", icon: "💻", mcqCount: 220, color: "#0F766E" },
];

export const sampleMCQs = [
  {
    id: 1,
    question: "Which city is the capital of Pakistan?",
    options: ["Lahore", "Karachi", "Islamabad", "Peshawar"],
    correct: 2,
    explanation: "Islamabad became the capital of Pakistan on 14 August 1967, replacing Karachi. It was purpose-built as the capital city.",
    subject: "Pakistan Studies",
    difficulty: "Easy",
  },
  {
    id: 2,
    question: "Who was the first Governor General of Pakistan?",
    options: ["Liaquat Ali Khan", "Khawaja Nazimuddin", "Quaid-e-Azam Muhammad Ali Jinnah", "Iskander Mirza"],
    correct: 2,
    explanation: "Quaid-e-Azam Muhammad Ali Jinnah became the first Governor General of Pakistan on 14 August 1947 and served until his death on 11 September 1948.",
    subject: "Pakistan Studies",
    difficulty: "Easy",
  },
  {
    id: 3,
    question: "What is the correct meaning of the word 'Ephemeral'?",
    options: ["Eternal and lasting", "Lasting for a very short time", "Related to the atmosphere", "A type of flower"],
    correct: 1,
    explanation: "Ephemeral means lasting for a very short time, transitory. For example: 'The ephemeral beauty of cherry blossoms.'",
    subject: "English Grammar",
    difficulty: "Medium",
  },
  {
    id: 4,
    question: "The Indus Waters Treaty was signed between Pakistan and India in which year?",
    options: ["1948", "1955", "1960", "1972"],
    correct: 2,
    explanation: "The Indus Waters Treaty was signed on September 19, 1960 in Karachi between Pakistan's President Ayub Khan and India's Prime Minister Jawaharlal Nehru, brokered by the World Bank.",
    subject: "Pakistan Studies",
    difficulty: "Medium",
  },
  {
    id: 5,
    question: "Which surah is known as the 'Heart of the Quran'?",
    options: ["Surah Al-Fatiha", "Surah Yaseen", "Surah Al-Baqarah", "Surah Al-Ikhlas"],
    correct: 1,
    explanation: "Surah Yaseen (Chapter 36) is known as the 'Heart of the Quran' (Qalb al-Quran) based on a hadith of the Prophet Muhammad (PBUH).",
    subject: "Islamiat",
    difficulty: "Easy",
  },
  {
    id: 6,
    question: "What is the speed of light in vacuum?",
    options: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"],
    correct: 1,
    explanation: "The speed of light in vacuum is approximately 3 × 10⁸ meters per second (299,792,458 m/s exactly). This is denoted by 'c'.",
    subject: "Everyday Science",
    difficulty: "Easy",
  },
];

export const stats = {
  totalJobs: 1250,
  totalMCQs: 45000,
  totalStudents: 89000,
  passRate: 73,
};

export const commissions = ["All", "FPSC", "PPSC", "SPSC", "NTS", "CSS", "KPPSC", "BPSC", "NPF"];

export const recentResults = [
  { name: "Ahmed K.", exam: "PPSC Sub-Inspector", score: 78, date: "3 days ago" },
  { name: "Fatima S.", exam: "FPSC Assistant Director", score: 85, date: "5 days ago" },
  { name: "Usman R.", exam: "NTS Network Eng.", score: 71, date: "1 week ago" },
  { name: "Zara M.", exam: "SPSC Junior Clerk", score: 90, date: "1 week ago" },
];
